apiVersion: v1 # String
kind: Pod # String
metadata: # Dictionary
  name: myapp-pod2
  labels: # Dictionary
    app: myapp  # Key value paids
spec:
  containers: # List
    - name: myapp
      image: stacksimplify/kubenginx:2.0.0
      ports: 
        - containerPort: 80
